export const IDPS = {
  STATUS: "0",
  COMANDS: "1",
  SCHEDULING_FULL_DATE: "2",
  SCHEDULING_FULL_ANGLE: "3",
  SCHEDULING_STOP_DATE: "4",
  SCHEDULING_STOP_ANGLE: "5",
  DEL_SCHEDULE: "6",
  GET_INITIAL_DATA: "1000",
  RSSI: "1001",
  ROUTE: "1002",
  NOISE: "1003",
  ALL_VARIABLES: "1004",
};
